#!/usr/bin/python

import os
import sys
import time
import argparse

def main():

  day_str = time.strftime("%A_%b%w_%Y")
  time_str = time.strftime("%I:%M %p")
  folder_path = os.path.join(os.path.expanduser('~'), 'devlogs')

  try:
    os.mkdir(folder_path)
  except:
    pass
  fn = '%s/%s.txt' % (folder_path, day_str)

  if args.read:
      try:
          f = open(fn, 'r')
          print f.read()
      except:
          print "No log created today :-("
      return
  text = raw_input()
  max_len = 69
  text_sections = []
  if len(text) <= max_len:
      text_sections = [text]
  else:
      words = text.split()
      while len(words):
          for i in range(len(words)):
              if len(' '.join(words[:i+1])) > max_len:
                  ind = i
                  break
          text_sections.append(' '.join(words[:ind]))
          words = words[ind:]

  final_text = '%s - %s\n' % (time_str, text_sections[0])

  if len(text_sections) > 1:
      final_text = '%s%s\n' % (final_text, '\n'.join(["%s%s" % ('           ', section) for section in text_sections[1:]]))

  with open(fn, 'a') as f:
     f.write(final_text)

if __name__=="__main__":
    parser = argparse.ArgumentParser(description='Dev Diary :-p')
    parser.add_argument('-r', '--read', action='store_true', help='Print out the contents of the current log')
    args = parser.parse_args();

    main()
